// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2vcDUAPaTtMrhbNdZMCtBIU8E-30o8Fc',
    appId: '1:296491893444:web:cb51d19a9a568e3d913f91',
    messagingSenderId: '296491893444',
    projectId: 'the-wall-c744b',
    authDomain: 'the-wall-c744b.firebaseapp.com',
    storageBucket: 'the-wall-c744b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh5aOWBNo_qkUlxnkiEhsmx8Nvd6m-_lU',
    appId: '1:296491893444:android:733fae33a13050fe913f91',
    messagingSenderId: '296491893444',
    projectId: 'the-wall-c744b',
    storageBucket: 'the-wall-c744b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1j4eKcbRvuEy_iRTUmJUO64Fh5NJDS_g',
    appId: '1:296491893444:ios:d73ff85a6dcae99a913f91',
    messagingSenderId: '296491893444',
    projectId: 'the-wall-c744b',
    storageBucket: 'the-wall-c744b.appspot.com',
    iosClientId: '296491893444-joqp8vla0nkph9ksctlkltjens20pglh.apps.googleusercontent.com',
    iosBundleId: 'com.example.wall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1j4eKcbRvuEy_iRTUmJUO64Fh5NJDS_g',
    appId: '1:296491893444:ios:d73ff85a6dcae99a913f91',
    messagingSenderId: '296491893444',
    projectId: 'the-wall-c744b',
    storageBucket: 'the-wall-c744b.appspot.com',
    iosClientId: '296491893444-joqp8vla0nkph9ksctlkltjens20pglh.apps.googleusercontent.com',
    iosBundleId: 'com.example.wall',
  );
}
